{% set name = "python-decouple" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2838cdf77a5cf127d7e8b339ce14c25bceb3af3e674e039d4901ba16359968c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -v

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - decouple
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/henriquebastos/python-decouple/
  doc_url: https://github.com/henriquebastos/python-decouple/blob/master/README.rst
  dev_url: https://github.com/henriquebastos/python-decouple/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Strict separation of config from code.
  description: |
    Decouple helps you to organize your settings so that you can change 
    parameters without having to redeploy your app.

extra:
  recipe-maintainers:
    - xmnlab
    - thewchan
