travis:
  secure:
    BINSTAR_TOKEN: RBbCayfnvmq5pAPtCP0hY5BjqPACzw/WlyHed8hWIZoKsQX+8FOsZgPZRiYnVsWs8PcIW5kEJZDZujdLASpESRoI+k/C3sSDTaY0dYQr/aTh89dYynnCVgxIsrn6zNRHuaPAq77RATu/SWIujx74gbckzjK9Zug4ZUfhTrNiV0t+qv0hgQ6rpSLua30fuU4+k65nZsqzOcHyHuKlEpSLrpq0y+DbPQfv3WKL02KUrr1FNq48ePy8EcHR7psHeErBVP8Hbmn7vMY6X0uOe3zQl4hpqaUJoSPYZDnGIVUvW7XhMjoguv1MvfbzICEml0vc5MICyN3LFq9rNHncCPSwBTe8nTs+tejPBs1tEr7zxf9YOrnPrQMuvJTAQ7DN6Tlh8kiOMXjybD0GqAxNvbegzM1w9D0FTWexiImCZie+VASX+FaKHNUfcWJBhMyutRuQjdTS6fh4Rw2LXhIYEDO8XsqePe0Pjm78WqZ4Ho4aIWt/7IjansiAyfmkiLSTJqtB7XrLcdfBY+BHFevkNyFXsrPns5CKZAVjAk+g/MkjGtubv4VC+0ZchRhc48+ZL+VRJbCwC9Sr+enD2fHCNpqXsO6uvntVAJcbOVI/caip4e/b4KXnI+Ulm/2sjU02afXfPvnVfXd3MgMNEVO5g6iSvIGGkwlFqZZRXgMe02e57tk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
