travis:
  secure:
    BINSTAR_TOKEN: BX5Cp6K59dX1TfO0PULfAfJ3lRgPIboos0kinenGI+LGgjb625n2GGbjnqHpBjjRHQJ88SntrCXnoe0bvxbJKpwFoCn80qHpt+JqW+Btgqpo4CpXw3vqp5mrB1IP4YmCTgS1aa3GrcNUfXIftMOBpFUYxbu88myIZXayR8GE3Spnl/Ry2T6j9d5tZ0ve8B+CJwxLPGollMTCBILCRQae+oom52hUpvWwYmTMjQLyTUyiWlji7BEwaqD3mny5/Is8UJXYdZ5gyAQkaOmVid/DVeZEpwIcwoHOJCbD9K+jSA8QgaArCRe21ppTnCLAxt/GylhXnMgoRDama4WfylWmGbe0C0ibHatYnrx6FcvhtPlZoNW0pVln4VPIlYpgXAHOGGx0Dm+Xql9QqZXdUtozLe3yQw1q1TYIquYfu2GgNgJKZxJFY/7XNpNmyR489sIPC8od2G3ko9QlX8ZvEvqG2/jy8PJItsFlHuzHg5cCrzfHxrNdyV2z/FyMyxFfnd4bzjRavx6Z1aKlD/yj25RaCGrpalQKKC8pSWQ3fVcK5CIvYXuwUlHkxZK9TK4fO8WGMFxcdFIbCIfsNrTMuJlnqtd1HCoBUBkKvxnd9h4XAGzXU08BGrg7sYK/NEYGsEpAaPKilPi5WtQaqm0Z9Nvv8zTCBooh6Z1g/eKBAYEGxFs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
